-- CreateTable
CREATE TABLE `Inscricao` (
    `id` VARCHAR(191) NOT NULL,
    `tipoCadastro` VARCHAR(191) NOT NULL,
    `nomeChapa` VARCHAR(191) NULL,
    `nomeEntidade` VARCHAR(191) NOT NULL,
    `segmento` ENUM('MOVIMENTO_DE_MORADIA', 'ENTIDADES_ACADEMICAS_DE_PESQUISA', 'ASSOCIACOES_DE_BAIRRO', 'MOVIMENTOS_AMBIENTALISTAS', 'SETOR_EMPRESARIAL') NOT NULL,
    `is_chapa` BOOLEAN NOT NULL,
    `nome` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `anexoPath` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
